# Generated by Django 2.0.7 on 2018-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2018-09-06'),
            preserve_default=False,
        ),
    ]
