# Generated by Django 2.0.7 on 2018-09-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20180910_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
